apiVersion: v2
name: springboot-demo
description: Spring Boot Helm chart for Kubernetes
home: xxx
type: application
sources:
  - xxx
version: 1.0.0
appVersion: 1.0.0
keywords:
- java
- spring-boot
maintainers:
- name: chenlong
  email: chenlong220192@gmail.com
